config/routes.rb
Cpdm::Application.routes.draw do
  resources :trackers

  get "start/index"

  get "analyzer/index"
  get "textminer/index", :as => :user_root
  root :to => 'start#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  

  

end

app/models/pattern.rb
class Pattern < ActiveRecord::Base
  belongs_to :user
end

app/models/tracker.rb
class Tracker < ActiveRecord::Base
  belongs_to :user
  
  
  
  require 'net/http'
  require 'uri'

  def self.tracking
    @trackers = Tracker.includes(:user).all
    if @trackers.present?
      @trackers.each do |tracker|
        request = self.http_request("get","http://133.242.171.135/evaluate_tweets_mongo.py",{:q=>tracker.queue, :token=>tracker.user.access_token, :secret=>tracker.user.access_token_secret})
      end
    end
    return
  end
  
  def self.http_request(method, uri, query_hash = {})
    uri = URI.parse(uri) if uri.is_a? String
    method = method.to_s.strip.downcase
    query_string = (query_hash||{}).map{|k,v|
      URI.encode(k.to_s) + "=" + URI.encode(v.to_s)
    }.join("&")

    if method == "post"
      args = [Net::HTTP::Post.new(uri.path), query_string]
    else
      args = [Net::HTTP::Get.new(uri.path + (query_string.empty? ? "" : "?#{query_string}"))]
    end

    Net::HTTP.start(uri.host, uri.port) do |http|
      return http.request(*args)
    end
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable #, :validatable
  has_many :patterns, :dependent => :destroy
  has_many :trackers, :dependent => :destroy
end

app/controllers/analyzer_controller.rb
class AnalyzerController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  http_basic_authenticate_with :name => "gingerale", :password => "drpepper"
  protect_from_forgery
 
end

app/controllers/patterns_controller.rb
class PatternsController < ApplicationController
  before_action :set_pattern, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /patterns
  # GET /patterns.json
  def index
  	@q = Pattern.search(params[:q])
  	@patterns = @q.result(distinct: true)
  end

  # GET /patterns/1
  # GET /patterns/1.json
  def show
  end

  # GET /patterns/new
  def new
    @pattern = Pattern.new
  end

  # GET /patterns/1/edit
  def edit
  end

  # POST /patterns
  # POST /patterns.json
  def create
    @pattern = current_user.patterns.build(pattern_params)

    respond_to do |format|
      if @pattern.save
        format.html { redirect_to @pattern, notice: 'Pattern was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pattern }
      else
        format.html { render action: 'new' }
        format.json { render json: @pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patterns/1
  # PATCH/PUT /patterns/1.json
  def update
    respond_to do |format|
      if @pattern.update(pattern_params)
        format.html { redirect_to @pattern, notice: 'Pattern was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patterns/1
  # DELETE /patterns/1.json
  def destroy
    @pattern.destroy
    respond_to do |format|
      format.html { redirect_to patterns_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pattern
      @pattern = Pattern.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pattern_params
      params.require(:pattern).permit(:user_id, :title, :context, :analysis_id, :consequence, :category, :example, :problem, :solution)
    end
end

app/controllers/start_controller.rb
class StartController < ApplicationController
  def index
    if current_user
  	  redirect_to :user_root
  	end
  end
end

app/controllers/textminer_controller.rb
class TextminerController < ApplicationController
  before_action :authenticate_user!
  def index
  end  
end

app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  before_action :set_tracker, only: [:show, :edit, :update, :destroy]

  # GET /trackers
  # GET /trackers.json
  def index
    @trackers = current_user.trackers
  end

  # GET /trackers/1
  # GET /trackers/1.json
  def show
  end

  # GET /trackers/new
  def new
    @tracker = Tracker.new
  end

  # GET /trackers/1/edit
  def edit
  end

  # POST /trackers
  # POST /trackers.json
  def create
    @tracker = current_user.trackers.build(tracker_params)

    respond_to do |format|
      if @tracker.save
        format.html { redirect_to trackers_path, notice: 'Tracker was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tracker }
      else
        format.html { render action: 'new' }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trackers/1
  # PATCH/PUT /trackers/1.json
  def update
    respond_to do |format|
      if @tracker.update(tracker_params)
        format.html { redirect_to trackers_path, notice: 'Tracker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trackers/1
  # DELETE /trackers/1.json
  def destroy
    @tracker.destroy
    respond_to do |format|
      format.html { redirect_to trackers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tracker
      @tracker = Tracker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tracker_params
      params.require(:tracker).permit(:user_id, :queue)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
 def twitter
    uid = env["omniauth.auth"]["uid"]
    user = User.find_by_uid(uid) || User.create!(:uid => uid, :name => env["omniauth.auth"]["info"]["nickname"], :access_token => env["omniauth.auth"]["credentials"]["token"], :access_token_secret => env["omniauth.auth"]["credentials"]["secret"])
    sign_in_and_redirect user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
  	  redirect_to :user_root
  	end
  end
end

app/helpers/analyzer_helper.rb
module AnalyzerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patterns_helper.rb
module PatternsHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/helpers/textminer_helper.rb
module TextminerHelper
end

app/helpers/trackers_helper.rb
module TrackersHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/views/analyzer/index.html.erb
<script type="text/javascript">
    // 棒グラフを表示する
	function renderChart(json, pn) {
		var data = d3.values(json.count);
		//var data = d3.csv.parse(d3.select('#csv').text());
		//console.log(data);
		var valueLabelWidth = 40; // space reserved for value labels (right)
		var barHeight = 20; // height of one bar
		var barLabelWidth = 150; // space reserved for bar labels
		var barLabelPadding = 5; // padding between bar and bar labels (left)
		var gridLabelHeight = 18; // space reserved for gridline labels
		var gridChartOffset = 3; // space between start of grid and first bar
		var maxBarWidth = 420; // width of the bar with the max value
 
		// accessor functions 
		var barLabel = function(d) { return d['name']; };
		var barValue = function(d) { return d[pn]; };

		// sorting
		var sortedData = data.sort(function(a, b) {
		 return d3.descending(barValue(a), barValue(b));
		}); 
		//console.log(sortedData);
		// scales
		var yScale = d3.scale.ordinal().domain(d3.range(0, sortedData.length)).rangeBands([0, sortedData.length * barHeight]);
		var y = function(d, i) { return yScale(i); };
		var yText = function(d, i) { return y(d, i) + yScale.rangeBand() / 2; };
		var x = d3.scale.linear().domain([0, d3.max(sortedData, barValue)]).range([0, maxBarWidth]);
		// svg container element
		var chart = d3.select('#chart').append("svg")
		  .attr('width', maxBarWidth + barLabelWidth + valueLabelWidth)
		  .attr('height', gridLabelHeight + gridChartOffset + sortedData.length * barHeight);
		// grid line labels
		var gridContainer = chart.append('g')
		  .attr('transform', 'translate(' + barLabelWidth + ',' + gridLabelHeight + ')'); 
		gridContainer.selectAll("text").data(x.ticks(10)).enter().append("text")
		  .filter(function(d) { return d[pn] > 1 })  
		  .attr("x", x)
		  .attr("dy", -3)
		  .attr("text-anchor", "middle")
		  .text(String);
		// vertical grid lines
		gridContainer.selectAll("line").data(x.ticks(10)).enter().append("line")
		  .filter(function(d) { return d[pn] > 1 })
		  .attr("x1", x)
		  .attr("x2", x)
		  .attr("y1", 0)
		  .attr("y2", yScale.rangeExtent()[1] + gridChartOffset)
		  .style("stroke", "#ccc");
		// bar labels
		var labelsContainer = chart.append('g')
		  .attr('transform', 'translate(' + (barLabelWidth - barLabelPadding) + ',' + (gridLabelHeight + gridChartOffset) + ')'); 
		labelsContainer.selectAll('text').data(sortedData).enter().append('text')
		  .attr('y', yText)
		  .attr('stroke', 'none')
		  .attr('fill', 'black')
		  .attr("dy", ".35em") // vertical-align: middle
		  .attr('text-anchor', 'end')
		  .text(barLabel);
		// bars
		var barsContainer = chart.append('g')
		  .attr('transform', 'translate(' + barLabelWidth + ',' + (gridLabelHeight + gridChartOffset) + ')'); 
		if (pn === 'nega') {
			barsContainer.selectAll("rect").data(sortedData).enter().append("rect")
		  	  .attr('y', y)
		  	  .attr('height', yScale.rangeBand())
		  	  .attr('width', function(d) { return x(barValue(d)); })
		      .attr('stroke', 'white')
		      .attr('fill', 'firebrick');
		} else {
			barsContainer.selectAll("rect").data(sortedData).enter().append("rect")
		  	  .attr('y', y)
		  	  .attr('height', yScale.rangeBand())
		  	  .attr('width', function(d) { return x(barValue(d)); })
		      .attr('stroke', 'white')
		      .attr('fill', 'royalblue');		
		};
		// bar value labels
		barsContainer.selectAll("text").data(sortedData).enter().append("text")
		  .attr("x", function(d) { return x(barValue(d)); })
		  .attr("y", yText)
		  .attr("dx", 3) // padding-left
		  .attr("dy", ".35em") // vertical-align: middle
		  .attr("text-anchor", "start") // text-align: right
		  .attr("fill", "black")
		  .attr("stroke", "none")
		  .style("class", "bar-value")
		  .text(function(d) { return d3.round(barValue(d), 2); });
		// start line
		barsContainer.append("line")
		  .attr("y1", -gridChartOffset)
		  .attr("y2", yScale.rangeExtent()[1] + gridChartOffset)
		  .style("stroke", "#000");

		if (pn === 'nega') {
			d3.selectAll('rect')
				.on('mouseover', function(d){
					d3.select(this)
						.transition()
						.attr("fill", "deeppink")				
				});
		
			d3.selectAll('rect')
				.on('mouseout', function(d){
					d3.select(this)
						.transition()
						.attr('fill', 'firebrick');
				});
		} else {
			d3.selectAll('rect')
				.on('mouseover', function(d){
					d3.select(this)
						.transition()
						.attr("fill", "skyblue")				
				});
		
			d3.selectAll('rect')
				.on('mouseout', function(d){
					d3.select(this)
						.transition()
						.attr('fill', 'royalblue');
				});
		
		}			
		d3.selectAll('rect')
        	.on('click', showText);
        
        d3.selectAll(".bar-value")
        	.on('click', showText);

	}
	// -----D3ここまで-----
	// onclickでツイートを表示する
	function showText(d) {
		$(document).ready(function () {
				$("#output").empty(); // ツイート表示領域を空にする
				for (var i in jsondata.noun) { // jsondata.nounは評価語、評価された属性、ツイートのリスト
					if (jsondata.noun[i].attr === d.name) { // 評価された属性 === 棒グラフのラベル名
						// #outputにツイートを追加する
						$("#output").append("<li><span class='" + jsondata.noun[i].pn +"'>【" + jsondata.noun[i].evaluate_word + "】</span><br />" + jsondata.noun[i].text + "</li>");
					}
				}
		})
	}
	
	// 細々した機能たち
	$(function() {
		// Enterが押下されたらsetJsondata()を実行する
		$("#query").keydown(function(evnt) {
			if(evnt.keyCode === 13) {
				setJsondata();
			}
		});	
		
		// プルダウンメニューが変更されたらrenderChart()を実行する
		$("select").change(function() {
			var pn = $('#pn').val();
			$("#chart").empty();
			$("#output").empty();
			renderChart(jsondata, pn);
		});
		//$('#key').exFlexFixed({
			//container : 'body'
		//});
	})


    </script>
	<style>
		.equal {
			fill: green;
			background-color: lightgreen;
			font-size: small;
		}
		.nega {
			fill: red;
			background-color: red;
			font-size: small;
		}
		.posi {
			fill: blue;
			background-color: lightblue;
			font-size: small;
		}
		li {
			font-size: small;
		}
		#loading {
			display: none;
		}
		#chart {
			width: 650px;
			float: left;
		}
		.user-img {
			float: left;
		}
	</style>
	<div id="container">
		<h1>ネガティブ評価は改善のきっかけ！(仮) ver0.1beta</h1>
		<p>
			<input type="text" id="query" size=30 />
			<input type="hidden" id="token" value="" />
			<input type="hidden" id="secret" value="" />
			<select id="pn" name="pn">
				<option value="posi">ポジティブな評価</option>
				<option value="nega" selected="selected">ネガティブな評価</option>
			</select>
			<input type="button" class="button" value="ついーとまいにんぐ！" onclick="setJsondata();" />
		</p>
		<p id="basic_info"></p>
		<div id="loading"><%= image_tag "turningIndicator.gif", :width=>"64px", :height=>"64px", :alt=>"Loading..." %></div>
		
		<div id="chart"></div>
		<div id="key"><ul id="output"></ul></div>
	</div>
    <%= javascript_tag do %>
    	function setJsondata() {
    		// フォームから値を取得
			var query = $('#query').val();
			var pn = $('#pn').val();
			// 二回目以降で前回の結果が残らないように空にする
			$("#chart").empty();
			$("#output").empty();
			$("#basic_info").empty();
			// ロード中のくるくるを表示する
			$("#loading").show();
		$.ajax({
			url: "http://133.242.171.135/evaluate_tweets.py",
			type: 'GET',
			data:{
				q:query,
				token:"<%=current_user.access_token%>",
				secret:"<%=current_user.access_token_secret%>"
			},
			dataType: "jsonp",
			success: function(data){
				var jsondata = data;
    			// ロード中のくるくるを消す
            	$("#loading").fadeOut();
            	// jsondataとポジネガを引数にD3で描画
            	renderChart(jsondata, pn);
            	// JSONからツイート何件、日時、とかを表示する部分
	           	$("#basic_info").append(
            		jsondata.basic_info.tweets_num + 
            		"件のツイートから評価語を含む" + 
            		jsondata.basic_info.evaluate_num + 
            		"件のツイートを分析<br />（取得期間 " + 
            		jsondata.basic_info.oldest_date + 
            		" から " + jsondata.basic_info.latest_date + "）");
			}
		});
		}
	<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title>みんなのデータ分析</title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

	<div class="container">
	<%= render 'shared/header' %>
    <%= yield %>
    <%= render 'shared/footer' %>
	</div>
    
  </body>
</html>

app/views/patterns/_form.html.erb
<%= form_for(@pattern) do |f| %>
  <div class="field">
    <%= f.text_field :title, :placeholder=>'パターン名' %>
  </div>
  <div class="field">
    <%= f.text_area :example, :placeholder=>'実際に活用された事例' %>
  </div>
  <div class="field">
    <%= f.text_area :context, :placeholder=>'Context' %>
  </div>
  <div class="field">
    <%= f.text_area :consequence, :placeholder=>'Consequence' %>
  </div>
  <div class="field">
    <%= f.select :category, [['アンケート',1],['A/Bテスト',2],['ソーシャル分析',1]] %>
  </div>
  <div class="field">
    <%= f.select :analysis_id, [['テキストマイニング',1],['t検定',2],['χ二乗検定',3]] %>
  </div>
  <div class="actions panel">
    <%= f.submit :class=>'button' %>
  </div>
<% end %>

app/views/patterns/_pattern.html.erb
<div class="small-6 columns">
	<ul class="pricing-table">
		<li class="title"><%= pattern.title %></li>
		<li class="description">Context</li>
		<li class="bullet-item"><%= pattern.context %></li>
		<li class="description">Problem</li>
		<li class="bullet-item"><%= pattern.problem %></li>
		<li class="description">Solution</li>
		<li class="bullet-item"><%= pattern.solution %></li>
		<li class="description">Consequence</li>
		<li class="bullet-item"><%= pattern.consequence %></li>
		<li class="cta-button"><%=link_to '閲覧する', pattern, :class=>'button' %></li>
	</ul>
</div>

app/views/patterns/edit.html.erb
<div class="row">
	<div class="panel">
		<h2>パターンを編集する</h2>
	</div>
	<%= form_for(@pattern) do |f| %>
	<div class="panel">
		<div class="small-8 columns">
		<%= f.text_field :title, :placeholder=>'パターン名' %>
		</div>
		<br>
		<%= f.text_area :example, :placeholder=>'実際に活用した例' %>
		<p>上にできるだけわかりやすくキャッチーなパターン名を書き入れ、実際に活用した例について記述してください。</p>
	</div>
	<div class="panel">
		<h4>分析したデータの型を選択してください。</h4>
		<%= f.select :category, [['アンケート(評価指数・選択式)',1],['アンケート(テキスト・自由回答)',2],['ソーシャルデータ(テキストマイニング)',1]] %>
	</div>
	<div class="panel">
		<h3><span class="label success">Context</span></h3> データ分析を行うにあたって生じた状況・前提について記述してください。<br>
		<%= f.text_area :context, :placeholder=>'Context' %>
	</div>
	<div class="panel">
		<h3><span class="label success">Problem</span></h3> データ分析を行う際に分析した問題・問いについて記述してください。<br>
		<%= f.text_area :problem, :placeholder=>'Problem' %>
	</div>
	<div class="panel">
		<h3><span class="label success">Solution</span></h3> どのデータ分析を行ったのか選択し, 分析方法について記述してください。<br>
		<%= f.select :analysis_id, [['テキスト分析(twitterのポジティブ・ネガティブ判定)',1],['t検定(二群の平均値の比較)',2],['χ二乗検定(二群の比率・分布の比較)',3]] %>
		<%= f.text_area :solution, :placeholder=>'Solution' %>
	</div>
	<div class="panel">
		<h3><span class="label success">Consequence</span></h3> データ分析を行ったことでどのような解釈ができ・結論を導けたのか、記述してください。<br>
		<%= f.text_area :consequence, :placeholder=>'Consequence' %>
	</div>
	<div class="panel">
		<%= f.submit '更新', :class=>'button' %> <%= link_to '一覧に戻る', patterns_path, :class=>'button secondary' %> <%= link_to 'パターンに戻る', @pattern, :class=>'button secondary' %>
	</div>
		<% end %>
</div>

app/views/patterns/index.html.erb
<div class="row">
	<div class="panel">
		<%= search_form_for @q do |f| %>
		<h4>あなたの調査形式、状況、得たい結果などを入力してください。</h4><br>
		<%= f.text_field :context_or_consequence_cont, :placeholder=>'ContextまたはConsequence' %><br>
		<%= f.submit '検索する', :class=>'button'%> <%= link_to '新しいパターンを作成', new_pattern_path, :class=>'button success' %>
		<% end %>
	</div>
	<%= render @patterns %>
</div>

app/views/shared/_header.html.erb
<nav class="top-bar">
	<% if current_user %>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "みんなのデータ分析", root_path %></a></h1>
    </li>
  </ul>
  <section class="top-bar-section">
	<% if current_user %>
    <ul class="right">
      <li class="divider"></li>
      <li><%= link_to "テキストマイニング", user_root_path %></li>
      <li class="divider"></li>
      <li><%= link_to "追跡機能", trackers_path %></li>
      <li class="divider"></li>
      <li><%= link_to "ログアウト", destroy_user_session_path, :method => :delete %></li>
    </ul>
    <% end %>
  </section>
  <% end %>
</nav>

app/views/trackers/index.html.erb
<div class="row">
	<div class="large-12 columns">
	<div id="container">
<h3>追跡ワード</h3>

<table>
  <thead>
    <tr>
      <th>あなたが追跡しているワード</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @trackers.each do |tracker| %>
      <tr>
        <td><%= tracker.queue %></td>
        <td><%= link_to '編集', edit_tracker_path(tracker) %></td>
        <td><%= link_to '削除', tracker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新しい追跡ワードを登録する', new_tracker_path %>

</div>
</div>
</div>

app/views/trackers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @tracker.user_id %>
</p>

<p>
  <strong>Queue:</strong>
  <%= @tracker.queue %>
</p>

<%= link_to 'Edit', edit_tracker_path(@tracker) %> |
<%= link_to 'Back', trackers_path %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<div class="row">
	<div class="large-9 columns">
		<div class="panel">
			<h1>みんなのデータ分析</h1>
			<p>問題解決のフレームワーク―パターン・ランゲージに沿って<br/>
			データ分析を行うことができるアプリケーションです。
			</p>
		</div>
		<div class="callout panel">
			<p>パターン・ランゲージは、建築家アレグザンダーが考案した問題解決のフレームワークです。<br/>
			Context, Problem, Solution, Consequenceの三つに課題解決のプロセスを分けることで<br/>
			似たような状況(Context)・問題(Problem)に陥ったときに誰でもパターン・ランゲージを<br/>
			用いれば、その状況・問題に解決策(Solution)を提案し、その結果(Consequence)を示すことができます。<br/><br/>
			そんなパターン・ランゲージを使うことで、「統計は苦手」「数字に弱い」<br/>
			という方でもテキストマイニング分析や統計分析を行える仕組みが<span class="label alert">みんなのデータ分析</span>です。		
			</p>
		</div>
	</div>
	<div class="large-3 columns">
		<ul class="pricing-table">
			<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
			<li class="bullet-item"><%= f.email_field :email,:placeholder=>'Email' %></li>
			<li class="bullet-item"><%= f.password_field :password,:placeholder=>'Password' %></li>
			<li class="bullet-item"><%= f.label :remember_me do %><%= f.check_box :remember_me, :class=>'custom checkbox'%> ログイン情報を記憶する<% end %></li>
			<li class="cta-button"><%= f.submit "ログイン", :class=>'button' %></li>
			<% end %>
			<li class="description">アカウントをお持ちでない場合は</li>
			<li class="cta-button"><%= link_to "登録", [ :new, :user_registration ], :class=>'button secondary' %></li>
		</ul>
	</div>
</div>